### ISSUE TITLE
想请问作者是否有繁体字的版本?

### ISSUE THREAD

**Issue by andy23andy7980** [contr4l/SimilarCharactor#10]
如题，
繁体跟简体有许多文字不同，因此想请教是否有繁体版本

**Comment by contr4l** [comment]
@andy23andy7980 

你好andy，繁体字的问题主要包括两点：
1. lazypinyin这个库是否能转换为正确的拼音（如果有音近字需求）
2. 四角码中是否有繁体字的信息，我认为70000字的那个库里应该有

除此之外，因为我原来写的这个toy project里，汉字的图片是通过网页爬虫获取的，我认为更优的做法是将汉字直接转换为图片，你可以尝试尝试。

工作繁忙，所以没有注意到你的issue，很抱歉。

**Comment by andy23andy7980** [comment]
感谢作者的回覆
祝福工作顺利

**Comment by contr4l** [comment]
> 感谢作者的回覆 祝福工作顺利

不客气！另外上面我记忆错误了，汉字的图片是通过pygame这个库进行转换的，详见：TransCharactor2Img.py
